# Generated by Django 5.2.5 on 2026-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0002_enrolmentratio_delete_advancementratio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessRateStipulatedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_entry', models.CharField(max_length=50)),
                ('n1_n2_n3_total', models.IntegerField()),
                ('passed_year_1', models.IntegerField(blank=True, null=True)),
                ('passed_year_2', models.IntegerField(blank=True, null=True)),
                ('passed_year_3', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
