# Generated by Django 5.2.5 on 2026-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0011_successrate_successratewithbacklogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformance4_3_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('X', models.FloatField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Z', models.IntegerField(default=0)),
            ],
        ),
    ]
