# Generated by Django 5.2.5 on 2026-02-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0012_academicperformance4_3_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('enrollment_no', models.CharField(max_length=20)),
                ('employer_name', models.CharField(max_length=200)),
                ('appointment_no', models.CharField(max_length=50)),
            ],
        ),
    ]
