# Generated by Django 5.2.5 on 2026-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0013_placementrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('event_name', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('professional_society', models.CharField(max_length=200)),
            ],
        ),
    ]
