# Generated by Django 5.2.5 on 2026-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0014_professionalactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_description', models.CharField(max_length=300)),
                ('year_of_publication', models.CharField(max_length=100)),
                ('issue_no', models.CharField(max_length=100)),
                ('editor_author', models.TextField()),
            ],
        ),
    ]
