# Generated by Django 5.2.5 on 2026-02-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0015_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_year', models.CharField(max_length=50)),
                ('type_of_activity', models.CharField(max_length=300)),
                ('date', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('organizing_body', models.CharField(max_length=300)),
                ('awards', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=100)),
                ('relevance_peos_pos', models.TextField()),
            ],
        ),
    ]
