# Generated by Django 5.2.5 on 2026-02-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion4', '0016_studentparticipation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPerformanceSecondYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(max_length=50, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('X', models.FloatField(default=0)),
                ('Y', models.IntegerField(default=0)),
                ('Z', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='AcademicPerformance',
        ),
        migrations.AlterField(
            model_name='studentspassedwithbacklogs',
            name='year_of_entry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='successrate',
            name='year_label',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='successratestipulatedperiod',
            name='year_of_entry',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='successratewithbacklogs',
            name='year_label',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
